let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let x = parseInt(input[0])
let y = parseInt(input[1])
let z = parseInt(input[2])
console.log((x + y <= z ? 1 : 0))
