let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let n = parseInt(input[0])
console.log(n % 5 === 0 ? parseInt(n / 5) : parseInt(n / 5) + 1)
