let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let num = Number(input[0])
console.log(parseInt((num - 1) * (num - 2) * (num - 3) / 6))
