let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let n = Number(input[0].split(' ')[0])
let k = Number(input[0].split(' ')[1])
let scores = input[1].split(' ').map(function (v) { return Number(v) })
scores.sort(function (a, b) { return b - a})
console.log(scores[k - 1])
