let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let array = input[0].split(' ').sort(function (a, b) { return Number(a) - Number(b) })
console.log(array[1])
