let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let a = Number(input[0])
let b = Number(input[1])
let c = Number(input[2])
console.log((a + b - c) + '\n' + (Number(a.toString() + b.toString()) - c))
