let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let x1 = Number(input[0].split(' ')[0])
let y1 = Number(input[0].split(' ')[1])
let x2 = Number(input[0].split(' ')[2])
let y2 = Number(input[0].split(' ')[3])
let x3 = Number(input[1].split(' ')[0])
let y3 = Number(input[1].split(' ')[1])
let x4 = Number(input[1].split(' ')[2])
let y4 = Number(input[1].split(' ')[3])
let xb = Math.max(x2, x4)
let xs = Math.min(x1, x3)
let yb = Math.max(y2, y4)
let ys = Math.min(y1, y3)
let max = Math.max((xb - xs), (yb - ys))
console.log(max * max)
