let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let n = Number(input[0].split(' ')[0])
let m = Number(input[0].split(' ')[1])
let k = Number(input[0].split(' ')[2])
let newN = parseInt(k / m)
let newM = parseInt(k % m)
console.log(newN + ' ' + newM)
