let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let firstBuckets = input[0].split(' ').map(function (v) { return parseInt(v)})
let secondBuckets = input[0].split(' ').map(function (v) { return parseInt(v)})
