let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let n = Number(input[0].split(' ')[0])
let r = Number(input[0].split(' ')[1])
let d = Number(input[0].split(' ')[2])
console.log(Math.ceil(n / (d - r)))