let fs = require('fs')
let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let a = Number(input[0].split(' ')[0])
let p = Number(input[0].split(' ')[1])
let c = Number(input[0].split(' ')[2])
console.log(Math.max(a+c, p))
