let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let a = BigInt(input[0].split(' ')[0])
let b = BigInt(input[0].split(' ')[1])
console.log((a + b).toString())
