let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let br = Number(input[0].split(' ')[0])
let bc = Number(input[0].split(' ')[1])
let dr = Number(input[1].split(' ')[0])
let dc = Number(input[1].split(' ')[1])
let jr = Number(input[2].split(' ')[0])
let jc = Number(input[2].split(' ')[1])
let b = Math.max(Math.abs(br - jr), Math.abs(bc - jc))
let d = Math.abs(dr - jr) + Math.abs(dc - jc)
console.log(b === d ? 'tie' : (b < d ? 'bessie' : 'daisy'))
