let fs = require('fs')
// let input = fs.readFileSync('/dev/stdin').toString().trim().split('\n')
let input = fs.readFileSync('test.txt').toString().trim().split('\n')
let a = Number(input[0].split(' ')[0])
let b = Number(input[0].split(' ')[1])
let v = Number(input[0].split(' ')[2])
let now = v / (a - b)
let temp = a / (a - b)
console.log(Math.ceil(now - temp + 1))
